### ISSUE TITLE
Tried calling: The method '[]' was called on null. Receiver: null Tried calling: []("image")

### ISSUE THREAD

**Issue by FredWolfe** [feMoraes0/food-bit-app#1]
class Details extends StatelessWidget {   static String page = 'details';   @override   Widget build(BuildContext context) {
    SizeConfig().init(context);
    final Map screenArguments = ModalRoute.of(context).settings.arguments;

    Map product = screenArguments['products'];
    int index = screenArguments['index'];

    return Scaffold(
      body: Stack(
        children: [
          Hero(
            tag: 'detail_food$index',
            child: Container(
              alignment: Alignment.topCenter,
              width: SizeConfig.screenWidth,
              height: SizeConfig.screenHeight,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: AssetImage(product['image']), //The error points here
                ),
              ),
            ),
          ),
          BodyDetails(),
        ],
      ),
    );   } }

can u please explain your code and update it... I am trying to establish the cart output

**Comment by feMoraes0** [comment]
Hello @FredWolfe, sorry but i won't update my code for now because I'm no longer supporting Flutter projects. I hope one day return for this dev-kit, but for now I can't. Explaining the code, Home widget send one of his products to details width with Hero animation, you can check it here:

```
File: food-bit-app/lib/app/tabs/home/
... line: 181
       Container(
          height: 220.0,
          child: ListView.builder(
            padding: const EdgeInsets.only(left: 10.0),
            scrollDirection: Axis.horizontal,
            itemCount: this.popularFood.length,
            itemBuilder: (context, index) {
              Map<String, String> product = this.popularFood[index];
              return GestureDetector(
                onTap: () {
                  Navigator.pushNamed(
                    context,
                    'details',
                    arguments: {
                      'product': product,
                      'index': index,
                    },
                  );
                },
                child: Hero(
                  tag: 'detail_food$index',
                  child: FoodCard(
                    width: size.width / 2 - 30.0,
                    primaryColor: theme.primaryColor,
                    productName: product['name'],
                    productPrice: product['price'],
                    productUrl: product['image'],
                    productClients: product['clients'],
                    productRate: product['rate'],
                  ),
                ),
              );
            },
          ),
... line 214
```
If the image appears on Home screen, should appear and trigger the animation to details widget too because they are local images used just for tests and demonstrations.
